spring:
  profiles.active: development

---
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto:
  datasource:
    url: jdbc:mysql://localhost:3306/mali-coin
    username: root
    password: root
server:
  port: 8087
---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/mali-coin
    username: root
    password: root
